# Generated by Django 3.2.5 on 2021-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_balance', models.FloatField()),
                ('coin_balance', models.FloatField()),
                ('win_rate', models.FloatField()),
            ],
        ),
    ]
